import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import { BrowserRouter, Route, Routes } from 'react-router';
import LandingPage from "./App.tsx";
import { DirectoryPage } from "@/features/directory/DirectoryPage.tsx";
import { SpecPage } from "@/features/spec-page/SpecPage.tsx";
import { Toaster } from "@/core/components/ui/sonner.tsx";
createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsxs(BrowserRouter, { children: [_jsx(Toaster, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(LandingPage, {}) }), _jsx(Route, { path: "/app", element: _jsx(DirectoryPage, {}) }), _jsx(Route, { path: "spec", children: _jsx(Route, { index: true, path: ":id", element: _jsx(SpecPage, {}) }) })] })] }) }));
